Resources:
  # Name of the table
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # We get the table name from the custom variable ${self:custom.tableName}.
      # This is generated dynamically in serverless.yml
      TableName: ${self:custom.tableName}
      # define 2 attributes (userId & noteId) and define them as primary key
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
